let quotes = [

  /* Version 1 */
  `Don't worry about what anybody else is going to do.<br> The best way to predict the future is to invent it.`,
  `No problem should ever have to be solved twice.`,
  `Attitude is no substitute for competence.`,
  `The real winner is the one who lives in today but able to see tomorrow.`,
  `Fools ignore complexity. Pragmatists suffer it.<br> Some can avoid it. Geniuses remove it.`,
  `Whatever you can do, or dream you can, begin it.<br> Boldness has genius, power, and magic in it.`,
  `Courage is grace under pressure.`,
  `Whenever you find yourself on the side of the majority,<br> it is time to pause and reflect.`,
  `As new powers are unleashed, you are initiated into higher levels of seeing the world.`,
  `Remember to keep the tension low, and the efficiency high`,
  `Keep your head on ice, and your heart on fire.`,

  /* Version 2 - Mastery [4/7/18] */
  `Practical knowledge is the ultimate commodity <br>and is what will pay you dividends for decades to come.`,
  `The ability to observe any unfamiliar environment will become a critical lifelong skill.`,
  `Begin with one skill that you can master and let that serve as a foundation for acquiring others.`,
  `Develop your powers of concentration;<br> Multitasking will be the death of the process.`,
  `Real pleasure comes from Overcoming challenges,<br> Feeling confidence in your abilities.<br>Gaining fluency in skills and Experiencing the power this brings.`,
  `The future belongs to those who learn more skills and combine them in creative ways.`,
  `You cannot make anything worthwhile in this world <br>unless you have first developed and transformed yourself.`,
  `When you are young:<br> Train yourself to get by with little money and<br>make the most of your youthful energy.`,
  `You must value learning above everything else.<br> This will lead you to all the right choices.`,
  `By valuing learning above all else,<br> You will set the stage for your creative expansion.<br>All else will follow.`,
  `If you want to learn and set yourself up for Mastery,<br> you have to do it yourself, and with great energy.`,
  `When you enter a new environment, your task is to learn and absorb as much as possible.`,
  `Value the process of self-discovery and make things that are of the highest quality.`,
  `Take full advantage of the openness of information and all of the knowledge at your disposal.`,
  `A man of talent is not born to be left to himself,<br> but to devote himself to art and good masters who will make something out of him.`,
  `To learn requires a sense of humility.`,
  `In the early stages of your career,<br> Acquire practical knowledge in the most efficient manner possible.`,
  `One repays a teacher badly if one remains only a pupil.`,
  `Live and let live.<br> Make use of those whom you cannot alter.`,
  `Pay attention to people's tone of voice, the look in their eyes, and their body language.`,
  `Actions say much more about their character, about what is going on underneath the surface.`,
  `Often it is the quiet ones, those who give out less at first glance, <br>who hide greater depths, that wield great power.`,
  `Intelligence is the most sensitive trigger point for envy.`,
  `Think of the workplace as a kind of theatre in which you are always wearing a mask.`,
  `Be careful in what you say. It is not worth the bother of freely expressing your opinions.`,
  `Rely upon yourself to get things done and you will not be disappointed.`,
  `Your work is the single greatest means at your disposal for expressing your social intelligence.`,
  `By making what you create easy to follow,<br> you show your care for the audience and public at large.`,
  `Excellent work is hard to argue with.`,
  `The personality we project to the world plays a substantial role in our success<br> and in our ascension to mastery.`,
  `Primary Law of the Creative Dynamic :<br>Your emotional commitment to what you are doing will be translated directly into your work.`,
  `The higher the goal, the more energy you will call up from deep within.`,
  `Cultivating the ability to endure and embrace uncertainties<br> will be the single most important factor in your success as a creative thinker.`,
  `Work hard to develop internal standards and a high degree of independence.`,
  `What must motivate you is the work itself and the process. <br>Public attention is acutally a nuisance and a distraction.`,
  `Never think about why you question. Simply never stop questioning.`,
  `The key to building anything right is repetition, repetition, repetition.`,
  `Principles of Mechanical Intelligence : <br> Whatever you are creating or designing, you must test and use yourself.`,
  `Whatever you produce has a life and presence of its own.`,
  `The real thinker sees the connections, <br>grasps the essence of the life force operating in every individual instance.`,
  `The mind was designed to connect things.`,
  `Mastery is following your natural inclinations and the deep desire that stirs you from within.`,
  `The desire within you is a deep expression of something natural, <br>Something that marked you at birth.`,
  `Genius does nothing but learn first how to lay bricks, then how to build, <br>and continually seek for material and continually form itself around it.`,


];
let getRandom = (floor, ceiling) => Math.floor(Math.random() * (ceiling - floor + 1) + floor);
let getQuote = () => quotes[getRandom(0, quotes.length - 1)];

document.querySelector('#quote').innerHTML = getQuote();
